language: node_js
node_js:
  - "6"

cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@5
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
